### ISSUE TITLE
transform is called twice on transform+filter

### ISSUE THREAD

**Issue by Xecutor** [simonask/rx-ranges#1]
Hi!

Here dead simple example code:

    #include <stdio.h>
    #include <vector>
    #include <rx/ranges.hpp>
    int main()
    {
      using namespace std;
      using namespace rx;
      vector<int> v = {1,2,3,4,5,6};
      auto r = v | rx::transform([](auto i){printf("tr=%d\n", i);return i*2;}) | filter([](auto i){return i>6;});
      for(auto i : r) {
        printf("for=%d\n", i);
      }
    }

I noticed that once filter condition is true, tr= is printed twice for each for= output. IMO it's not really expected behaviour and looks like overhead.

**Comment by Hazurl** [comment]
https://github.com/simonask/rx-ranges/blob/master/include/rx/ranges.hpp#L696
`filter` will always call `range.get()` two times on accepted element as it skips them until one suitable is found.

To compensate that, either `filter` should cache the value (like in `generate`) or a custom range/transformer just before `filter` should take care of it.

**Comment by simonask** [comment]
@Xecutor This issue should be fixed in version 2.0 (#10).
