### ISSUE TITLE
Make months in calendar constexpr

### ISSUE THREAD

**Issue by Hazurl** [simonask/rx-ranges#38]
Discussion: https://github.com/simonask/rx-ranges/commit/ec887555b11124fe18c1e32e497699d933c9a558#r36088781

But basically changing [the definition of `s_months_names`](https://github.com/simonask/rx-ranges/blob/dd02d0e1ae3bf0b05b53d6ff248052f8c7f3b2bf/test/calendar.cpp#L17) to be `constexpr` and avoid the runtime cost.

**Comment by simonask** [comment]
No reason not to AFAICT :)

**Comment by simonask** [comment]
Fixed by #39
