### ISSUE TITLE
VS2017 won't compile without Conformance Mode

### ISSUE THREAD

**Issue by tkozybski** [simonask/rx-ranges#7]
As in the title. Not sure if can be marked as bug, but at least it's worth mentioning in the requirements.

Example Code and Console Output

```
#include "pch.h"
#include "ranges.hpp"
#include <iostream>
#include <vector>

template <typename Type>
struct Point {

    Point(Type x, Type y) noexcept
        : X { x }
        , Y { y }
    {
    }

    Type X;
    Type Y;
};

int main()
{
    std::vector<Point<int>> vec;
    vec.emplace_back(1, 2);
    vec.emplace_back(2, 3);
    vec.emplace_back(3, 4);

    auto transformed = vec
        | rx::filter([](Point<int> point) { return point.X == 3; })
        | rx::transform([](Point<int> point) { return point.X; })
        | rx::to_vector();

    for (auto x : transformed) {
        std::cout << x << '\n';
    }
}
```

```
1>c:\users\tomek\source\repos\consoleapplication7\consoleapplication7\ranges.hpp(1476): error C2133: 'vec': unknown size
1>c:\users\tomek\source\repos\consoleapplication7\consoleapplication7\ranges.hpp(235): note: see reference to function template instantiation 'auto rx::to_vector::operator ()<LHS>(R &&) const' being compiled
1>        with
1>        [
1>            LHS=rx::transform<main::<lambda_5eaf32db83d37af66b6c17510f1a5e05>>::Range<Inner>,
1>            R=rx::transform<main::<lambda_5eaf32db83d37af66b6c17510f1a5e05>>::Range<Inner>
1>        ]
1>c:\users\tomek\source\repos\consoleapplication7\consoleapplication7\ranges.hpp(1476): error C2512: 'std::vector<remove_cv<remove_reference<remove_cv<_Ty>::type::output_type>::type>::type,std::allocator<remove_cv<remove_reference<remove_cv<_Ty>::type::output_type>::type>::type>>': no appropriate default constructor available
1>        with
1>        [
1>            _Ty=remove_reference<unknown-type>::type
1>        ]
1>c:\users\tomek\source\repos\consoleapplication7\consoleapplication7\ranges.hpp(1476): note: see declaration of 'std::vector<remove_cv<remove_reference<remove_cv<_Ty>::type::output_type>::type>::type,std::allocator<remove_cv<remove_reference<remove_cv<_Ty>::type::output_type>::type>::type>>'
1>        with
1>        [
1>            _Ty=remove_reference<unknown-type>::type
1>        ]
1>c:\users\tomek\source\repos\consoleapplication7\consoleapplication7\ranges.hpp(1477): fatal error C1903: unable to recover from previous error(s); stopping compilation
```

**Comment by Trass3r** [comment]
You mean `/permissive-`?

**Comment by tkozybski** [comment]
Yes

**Comment by simonask** [comment]
I'm confused: Does it work with or without `/permissive-`? We build the tests and benchmarks with `/permissive-`, and I would be rather surprised to see something compile in non-permissive mode that does compile in permissive mode. Still, would not be the first time MSVC surprised me...

@tkozybski Can you check if this is still a problem in the version 2.0 branch (#10)?

**Comment by tkozybski** [comment]
> I'm confused: Does it work with or without `/permissive-`? We build the tests and benchmarks with `/permissive-`, and I would be rather surprised to see something compile in non-permissive mode that does compile in permissive mode. Still, would not be the first time MSVC surprised me...
> 
> @tkozybski Can you check if this is still a problem in the version 2.0 branch (#10)?

@simonask  IIt doesn't compile if Conformance Mode is set to "No", with 2.0 as well. It does compile with VS2019 though (platform toolset v142, doesn't work on v141).

**Comment by simonask** [comment]
Ah, now I see. I'll take a look at it. :-)

**Comment by simonask** [comment]
Ok, the issue seems to be that VS2017 does not parse C++17 fold expressions correctly. Microsoft claims that the latest versions of VS2017 had a number of bugs fixed related to fold expressions, but apparently not enough, which is unfortunate.

@tkozybski Is using VS2019 not an option for you?

I am closing this for now, since supporting buggy compilers is not a goal.

**Comment by Trass3r** [comment]
It fails without that mode too: https://godbolt.org/z/N8T5n5

> @tkozybski Is using VS2019 not an option for you?

Yep, since they are binary compatible there's no good reason not to.

**Comment by Kijewski** [comment]
Version 2.0 works in MSVC 19.20 and higher: https://godbolt.org/z/ryyBvJ
